### ISSUE TITLE
Axe duplicating from toolbar

### ISSUE THREAD

**Issue by karstenbeebe** [RubixDev/Inventorio#316]
When using the axe from the tool bar, it will duplicate into the hotbar slot you have selected. This can also cause the item you are holding to be replaced with your axe

**Comment by karstenbeebe** [comment]
This has been happening on my server for version 1.20.4 on Fabric - Inventorio v1.9.3

**Comment by Enderteck** [comment]
Somae problem on Neoforge 101 for 1.20.1 with Inventorio 1.9.2. It doesn't really duplicate it most of the time but just puts the item in the currently used slot.

Replaces anything and makes me loose items. 

It also appears in the tool belt at the same time but it's a visual glitch as it's not really there when it teleports to my toolbar and gets upated when you click on it or on the tool itself.

**Comment by Enderteck** [comment]
I squggest renaming to [Important] Item teleportation/duplication,

as it doesn't affect just axes.

**Comment by RubixDev** [comment]
this sounds like some sort of incompatibility with another mod as I have not experienced that myself yet. Could either of you figure out which mod is causing this or at least provide a list of other mods you have installed?

**Comment by Enderteck** [comment]
Couldn't find any mods that were causing the problem but it might be the sophisticated suite as it has bugs rn: 

https://github.com/P3pp3rF1y/SophisticatedCore/issues/218.

Here is my mod list where it sometimes happened:

Neoforge 47.1.101 for minecraft 1.20.1

Mods:
  [✔] AdditionalPlacements-1.20-1.8.0
  [✔] BetterAdvancements-1.20.1-0.3.2.162
  [✔] BetterF3-7.0.2-Forge-1.20.1
  [✔] BetterThirdPerson-Forge-1.20-1.9.0
  [✔] BiomesOPlenty-1.20.1-18.0.0.598
  [✔] Bookshelf-Forge-1.20.1-20.1.9
  [✔] BotanyPots-Forge-1.20.1-13.0.25
  [✔] BotanyTrees-Forge-1.20.1-9.0.11
  [✔] Chipped-forge-1.20.1-3.0.4
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] Copycats-forge.1.20.1-1.2.0
  [✔] CraftTweaker-forge-1.20.1-14.0.36
  [✔] Create-Dreams-n-Desires-1.20.1-0.2c.PREBETA
  [✔] CreativeCore_FORGE_v2.11.25_mc1.20.1
  [✔] Cucumber-1.20.1-7.0.7
  [✔] CutThrough-v8.0.2-1.20.1-Forge
  [✔] Delightful-1.20.1-3.5.2
  [✔] EggDelight-v1.2-1.20.1
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.0.14
  [✔] EnderIO-1.20.1-6.0.25-alpha
  [✔] FarmersDelight-1.20.1-1.2.4
  [✔] ForgeConfigScreens-v8.0.2-1.20.1-Forge
  [✔] HammerLib-1.20.1-20.1.25
  [✔] ImmersiveEngineering-1.20.1-10.0.0-169
  [✔] ItemPhysic_FORGE_v1.7.0_mc1.20.1
  [✔] Jade-1.20.1-forge-11.8.0
  [✔] JadeAddons-1.20.1-forge-5.2.2
  [✔] Mekanism-1.20.1-10.4.6.20
  [✔] MekanismAdditions-1.20.1-10.4.6.20
  [✔] MekanismGenerators-1.20.1-10.4.6.20
  [✔] MekanismTools-1.20.1-10.4.6.20
  [✔] MoreMekanismProcessing-1.20.1-4.0
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] NaturesCompass-1.20.1-1.11.2-forge
  [✔] OreBerries-Replanted-1.20.1-0.5.2
  [✔] Patchouli-1.20.1-84-FORGE
  [✔] Paxi-1.20-Forge-4.0
  [✔] Powah-5.0.5
  [✔] PuzzlesLib-v8.1.17-1.20.1-Forge
  [✔] Quark-4.0-438
  [✔] QuarkOddities-1.20.1
  [✔] REIPluginCompatibilities-forge-12.0.93
  [✔] RapidLeafDecay-1.20.1-2.0.2
  [✔] Rats-1.20.1-8.1.2
  [✔] RoughlyEnoughItems-12.0.684-forge
  [✔] Searchables-forge-1.20.1-1.0.2
  [✔] SolarFluxReborn-1.20.1-20.1.5
  [✔] Steam_Rails-1.5.3+forge-mc1.20.1
  [✔] TerraBlender-forge-1.20.1-3.0.1.4
  [✔] Terralith_1.20.4_v2.4.11
  [✔] ThirstWasTaken-1.20.1-1.3.6
  [✔] Twilight Flavors & Delight-2.0.1
  [✔] XaerosWorldMap_1.38.1_Forge_1.20
  [✔] Xaeros_Minimap_24.0.1_Forge_1.20
  [✔] YungsApi-1.20-Forge-4.0.4
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterDungeons-1.20-Forge-4.0.3
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.5
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.4
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] YungsBetterStrongholds-1.20-Forge-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.3
  [✔] YungsBridges-1.20-Forge-4.0.3
  [✔] Zeta-1.0-14
  [✔] alexscaves-1.1.4
  [✔] alexsmobs-1.22.8
  [✔] amendments-1.20-1.1.10
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] architectury-9.2.14-forge
  [✔] athena-forge-1.20.1-3.1.2
  [✔] balm-forge-1.20.1-7.2.2
  [✔] bbs-1.20.1-0.1.3-forge
  [✔] bellsandwhistles-0.4.3-1.20.x
  [✔] bettercrafting-1.20.1-15-forge
  [✔] carryon-forge-1.20.1-2.1.2.7
  [✔] catalogue-forge-1.20.1-1.8.0
  [✔] cfm-forge-1.20.1-7.0.0-pre36
  [✔] citadel-2.5.4-1.20.1
  [✔] citresewn-1.20.1-5
  [✔] cloth-config-11.1.118-forge
  [✔] cofh_core-1.20.1-11.0.0.51
  [✔] collective-1.20.1-7.40
  [✔] comforts-forge-6.3.5+1.20.1
  [✔] compressedcreativity-1.20.1-0.1.8.b
  [✔] cookingforblockheads-forge-1.20.1-16.0.3
  [✔] corn_delight-1.0.3-1.20.1
  [✔] corpse-forge-1.20.1-1.0.12
  [✔] crafting+-1.1
  [✔] craftingtweaks-forge-1.20.1-18.2.3
  [✔] create-1.20.1-0.5.1.f
  [✔] create-structures-0.1.1-1.20.1-FORGE
  [✔] create-stuff-additions1.20.1_v2.0.4a
  [✔] create-track-map-1.4+mc1.20.1-neoforge
  [✔] create_connected-0.7.3-mc1.20.1-all
  [✔] create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.8
  [✔] create_misc_and_things_ 1.20.1_4.0A
  [✔] create_power_loader-1.4.0-mc1.20.1
  [✔] createaddition-1.20.1-1.2.2
  [✔] createdeco-2.0.1-1.20.1-forge
  [✔] createdieselgenerators-1.20.1-1.2h
  [✔] createendertransmission-2.0.7-1.20.1
  [✔] createutilities-0.2.0+1.20.1
  [✔] curios-forge-5.7.2+1.20.1
  [✔] dynamiclights-v1.7.1-mc1.17x-1.20x-mod
  [✔] eatinganimation-1.20-5.0.0
  [✔] embeddium-0.3.9+mc1.20.1
  [✔] emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge
  [✔] entity_model_features_forge_1.20.1-1.3
  [✔] entity_texture_features_forge_1.20.1-5.2.3
  [✔] entityculling-forge-1.6.2-mc1.20.1
  [✔] essential_1-3-1-1_forge_1-20-1
  [✔] everycomp-1.20-2.6.36
  [✔] extractinator-forge-1.20.1-2.3.0
  [✔] ferritecore-6.0.1-forge
  [✔] framework-forge-1.20.1-0.6.16
  [✔] ftb-library-forge-2001.1.5
  [✔] ftb-ultimine-forge-2001.1.4
  [✔] garnished-1.7.2+1.20.1
  [✔] gml-4.0.9-all
  [✔] goldenhopper-forge-1.20.1-1.4.1
  [✔] handcrafted-forge-1.20.1-3.0.6
  [✔] interiors-0.5.2+mc1.20.1-FORGE
  [✔] inventorio-1.20-forge-1.9.2
  [✔] ironfurnaces-1.20.1-4.1.6
  [✔] itlt-1.20.01-2.2.1
  [✔] iwannaskate-1.2.0
  [✔] kotlinforforge-4.10.0-all
  [✔] littlecontraptions-forge-1.20.1.2
  [✔] littlelogistics-mc1.20.1-v1.20.1.2
  [✔] lootr-1.20-0.7.31.78
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] mighty_mail-forge-1.20.1-1.0.14
  [✔] modelfix-1.14
  [✔] modernfix-forge-5.14.0+mc1.20.1
  [✔] moonlight-1.20-2.11.4-forge
  [✔] mysterious_mountain_lib-1.4.4-1.20.1
  [✔] notenoughanimations-forge-1.7.1-mc1.20.1
  [✔] oculus-mc1.20.1-1.6.15a
  [✔] player-animation-lib-forge-1.0.2-rc1+1.20
  [✔] pneumaticcraft-repressurized-6.0.14+mc1.20.1
  [✔] polymorph-forge-0.49.2+1.20.1
  [✔] refinedcooking-4.0.0
  [✔] refinedstorage-1.12.4
  [✔] refinedstorageaddons-0.10.0
  [✔] resourcefulconfig-forge-1.20.1-2.1.2
  [✔] resourcefullib-forge-1.20.1-2.1.23
  [✔] right_click_get_crops-1.20.1-1.6.0.12
  [✔] rubidium-extra-0.5.4.2+mc1.20.1-build.118
  [✔] sebastrnlib-4.0.0
  [✔] shetiphiancore-forge-1.20.1-1.2
  [✔] sliceanddice-forge-3.2.0
  [✔] sophisticatedbackpacks-1.20.1-3.20.2.1022
  [✔] sophisticatedcore-1.20.1-0.6.8.567
  [✔] sophisticatedstorage-1.20.1-0.10.8.752
  [✔] sunflowerdelight-1.20.1-1.0.1
  [✔] supplementaries-1.20-2.8.6
  [✔] suppsquared-1.20-1.1.14
  [✔] tectonic-mod-1.19.3-v2.2.1
  [✔] textrues_embeddium_options-0.1.5+mc1.20.1
  [✔] thermal_cultivation-1.20.1-11.0.0.22
  [✔] thermal_dynamics-1.20.1-11.0.0.21
  [✔] thermal_expansion-1.20.1-11.0.0.27
  [✔] thermal_foundation-1.20.1-11.0.2.64
  [✔] thermal_innovation-1.20.1-11.0.0.21
  [✔] thermal_integration-1.20.1-11.0.0.23
  [✔] thermal_locomotion-1.20.1-11.0.0.17
  [✔] tia-1.20-1.1-forge
  [✔] twilightforest-1.20.1-4.3.2145-universal
  [✔] visuality-forge-2.0.2
  [✔] voicechat-forge-1.20.1-2.5.9
  [✔] waterframes-1.20.1-2.0.0-beta5.1
  [✔] watermedia-2.0.27-beta
  [✔] waystones-forge-1.20-14.1.3
  [✔] yet-another-config-lib-forge-3.2.2+1.20

I'm not 100% sure it happened on these Sophisticated core, storage and backpacks version as I had to roll back to a tiny bit older release to play without this [bug](https://github.com/P3pp3rF1y/SophisticatedCore/issues/218.).

**Comment by Enderteck** [comment]
Here is a vid of it happening again. I lost my Create Backpack :(

[Screen-Recording.webm](https://github.com/RubixDev/Inventorio/assets/123917079/d4b5b058-b152-4566-8ef0-88c66f529327)

**Comment by RubixDev** [comment]
@Enderteck I just closed #230 and that might maybe have also fixed this issue. Could you maybe download the build artifacts of the [latest CI run](https://github.com/RubixDev/Inventorio/actions/runs/8445763118) and see if this is still present? I personally still haven't been able to reproduce this.

**Comment by Enderteck** [comment]
I will thx

**Comment by Enderteck** [comment]
It seems fixed to me. I will try it more in depth and tell you if I find any issue.

**Comment by Enderteck** [comment]
This version crashes on servers tho. Don't release it yet.

[Crash report](https://mclogs.minestrator.com/D1r2jij)

**Comment by RubixDev** [comment]
> This version crashes on servers though. Don't release it yet.

Thanks for pointing that out! Try if https://github.com/RubixDev/Inventorio/actions/runs/8460300126 fixes that.

**Comment by RubixDev** [comment]
Great, thank you!

**Comment by Enderteck** [comment]
It happended again unforunately,

here's the entire server log from when I joined untill I left the server:

[latest.log](https://mclo.gs/G2C2QPZ)

Here's the log from the server start to the "preparing Spawn area" line:

[latest.log](https://mclo.gs/ItCqqAP)

Here's the mod list extracted:

https://pastebin.com/nRRq30jT

**Comment by Enderteck** [comment]
Here's an example that happens every time, the Quark Pickarang:

[Screen-Recording.webm](https://github.com/RubixDev/Inventorio/assets/123917079/d00d6db3-993d-4e28-bba4-f2e21af18316)

**Comment by RubixDev** [comment]
The Quark Pickarang should be fixed now (you can try yourself with the build artifacts from [here](https://github.com/RubixDev/Inventorio/actions/runs/8549047096)), but I'm leaving this issue open as the Pickarang issue was one specific case which has now specifically been worked around. The other cases will probably still exist.

Would you perhaps also be able to provide me with a modpack or Prism Launcher instance that contains all the mods? That would save me quite some time compared to having to download each mod one by one.

**Comment by Enderteck** [comment]
> The Quark Pickarang should be fixed now (you can try yourself with the build artifacts from [here](https://github.com/RubixDev/Inventorio/actions/runs/8549047096)), but I'm leaving this issue open as the Pickarang issue was one specific case which has now specifically been worked around. The other cases will probably still exist.
> 
> Would you perhaps also be able to provide me with a modpack or Prism Launcher instance that contains all the mods? That would save me quite some time compared to having to download each mod one by one.

Sorry I didn't respond, sure I'll send my Modpack !

**Comment by SonyStinks** [comment]
Not to make matters worse, but "this bug still happens to me all the time on my server."

It does not matter what tool I use, as long as it fits into the tool belt slot.

Having an item in the offhand utility belt seems to make it worse.  To duplicate, all I have to do is just use the tool for more than 30 seconds or so--or swap intensively to/from for about 1 minute.  I  now obsess over keeping a hot bar slot empty just so I can use my tools.

The modpack I'm working through uses Sophisticated Core + Sophisticated Storage, but no Sophisticated Backpacks.  It also has a stack-refilling mod called "Stack Refill" installed.

It would be really nice if the tool swapping event would just make a temporary inventory slot for whatever hot bar item it was replacing, swap the item into that while using the tool, and then put it back when it's done.  That way, I'd not have to keep worrying about losing my precious things to a duplication bug, and the worst-case scenario would be an item getting auto-dropped instead of disappearing. Or maybe just keep the extra slot until the hot bar space is freed up manually again. That'd be cool, too.  Just my opinion, though.

Relevant info:

Modpack: NeoForge Foundry - StoneFactory Edition v0.6.0
OS: Ubuntu Linux 24.04 LTS (noble)
Mod Loader: NeoForge 20.4.237
Minecraft version: 1.20.4
Java version: Oracle proprietary JDK 21.0.4 "x64"

Feel free to contact me over GitHub if there's something I can test out for you.  I hope you can squash this bug fully and forever!
